"""init_db_with_multiline_orders

Revision ID: 36731b32c090
Revises: 
Create Date: 2026-06-28 14:30:31.109409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36731b32c090'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="Наименование типа (напр. 'Конденсатор')"),
    sa.Column('part_number', sa.String(), nullable=False, comment='Manufacturer Part Number (MPN)'),
    sa.Column('category', sa.String(), nullable=True, comment='Категория (Резисторы, Микросхемы и т.д.)'),
    sa.Column('package', sa.String(), nullable=True, comment='Тип корпуса (0603, SOT-23, LQFP-64)'),
    sa.Column('value', sa.String(), nullable=True, comment="Номинальное значение (напр. '10uF', '4.7k')"),
    sa.Column('value_numeric', sa.Float(), nullable=True, comment="Приведенное значение (напр. '10000.0')"),
    sa.Column('voltage', sa.Float(), nullable=True, comment='Рабочее напряжение, В'),
    sa.Column('specifications', sa.JSON(), nullable=True, comment='Дополнительные характеристики в формате JSON'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_category'), 'components', ['category'], unique=False)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_package'), 'components', ['package'], unique=False)
    op.create_index(op.f('ix_components_part_number'), 'components', ['part_number'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False, comment='Наименование заказчика / контрагента.'),
    sa.Column('status', sa.String(), nullable=True, comment='Этап: In Progress -> In Production -> Completed.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Время постановки в очередь.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="Понятное имя (напр. 'Плата управления двигателем')"),
    sa.Column('sku', sa.String(), nullable=True, comment='Внутренний код/артикул готового товара'),
    sa.Column('drawing_number', sa.String(), nullable=True, comment='Децимальный номер по ГОСТ (напр. РСДТ...)'),
    sa.Column('is_subassembly', sa.Boolean(), nullable=True, comment='True, если это не готовый продукт, а вложенный узел (полуфабрикат).'),
    sa.Column('revision', sa.String(), nullable=True, comment='Версия КД или ревизия печатной платы.'),
    sa.Column('bill_of_materials_url', sa.String(), nullable=True, comment='Путь к чертежам, PDF или исходникам проекта.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Технические особенности или нюансы сборки.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_types_drawing_number'), 'product_types', ['drawing_number'], unique=False)
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.create_index(op.f('ix_product_types_sku'), 'product_types', ['sku'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('bom_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_name', sa.String(), nullable=False, comment="Строка-ключ (напр. 'Конденсатор ССО603...'). Основа для поиска."),
    sa.Column('component_id', sa.Integer(), nullable=True, comment='Ссылка на складскую позицию. NULL, если сопоставление не выполнено.'),
    sa.Column('mapping_type', sa.String(), nullable=True, comment="Тип привязки: 'auto' (робот) или 'manual' (человек)."),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Подтверждено ли сопоставление ответственным лицом.'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_mappings_design_name'), 'bom_mappings', ['design_name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False, comment='SN изделия.'),
    sa.Column('test_result', sa.String(), nullable=True, comment='Результат прохождения ОТК.'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_order_id'), 'items', ['order_id'], unique=False)
    op.create_index(op.f('ix_items_serial_number'), 'items', ['serial_number'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Ссылка на главный заказ'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Ссылка на собираемое изделие'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='План выпуска данного изделия (штук).'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('product_boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='Владелец спецификации'),
    sa.Column('design_name', sa.String(), nullable=False, comment='Текст из ПЭ3. Позволяет хранить состав даже без привязки к складу.'),
    sa.Column('designators', sa.String(), nullable=True, comment='Адреса на плате (напр. R1, R5-R10). Важно для монтажников.'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='ID ресурса. Ссылается на Component или ProductType (зависит от типа).'),
    sa.Column('resource_type', sa.String(), nullable=False, comment="Дискриминатор: 'component' (покупное) или 'product' (свой узел)."),
    sa.Column('quantity', sa.Float(), nullable=False, comment='Количество на 1 шт. готового изделия.'),
    sa.Column('is_resolved', sa.Boolean(), nullable=True, comment='Маркер готовности: найдена ли деталь в складской базе.'),
    sa.ForeignKeyConstraint(['product_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_boms_design_name'), 'product_boms', ['design_name'], unique=False)
    op.create_index(op.f('ix_product_boms_resource_id'), 'product_boms', ['resource_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False, comment='Количество забронированных единиц.'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_component_id'), 'reservations', ['component_id'], unique=False)
    op.create_index(op.f('ix_reservations_order_id'), 'reservations', ['order_id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('actual_qty', sa.Float(), nullable=True, comment='Текущее количество на складе'),
    sa.Column('location', sa.String(), nullable=True, comment='Адрес хранения (стеллаж, ячейка)'),
    sa.Column('reserved_qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_reservations_order_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_component_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_product_boms_resource_id'), table_name='product_boms')
    op.drop_index(op.f('ix_product_boms_design_name'), table_name='product_boms')
    op.drop_table('product_boms')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_items_serial_number'), table_name='items')
    op.drop_index(op.f('ix_items_order_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_bom_mappings_design_name'), table_name='bom_mappings')
    op.drop_table('bom_mappings')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_product_types_sku'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_drawing_number'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_components_part_number'), table_name='components')
    op.drop_index(op.f('ix_components_package'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_category'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
